# This is a TOML document. Boom
debug = true

logicServiceName = "im-biz-rpc"

[rpcServer]
    addr = ":2003"
    timeout = "1s"

[tcp]
    bind = [":2004"]
    sndbuf = 4096
    rcvbuf = 4096
    keepalive = false
    reader = 32
    readBuf = 1024
    readBufSize = 8192
    writer = 32
    writeBuf = 1024
    writeBufSize = 8192

[websocket]
    bind = [":2005"]
    tlsOpen = false
    tlsBind = [":2006"]
    certFile = "../examples/cert.pem"
    privateFile = "../examples/private.pem"

[protocol]
    timer = 32
    timerSize = 2048
    svrProto = 10
    cliProto = 5
    handshakeTimeout = "15s"  # 握手超时时间

[whitelist]
    Whitelist = [123] # mid
    WhiteLog  = "/tmp/white_list.log"

[bucket]
    size = 32
    channel = 1024
    room = 1024
    routineAmount = 32
    routineSize = 1024
