# 七牛对象存储
# 这里用到了三个不同的桶，为了更好的分配资源，可以为不同的桶设置不同的桶策略。
# video 前缀的桶：用于存储视频
# im 前缀的桶：存储一些其他持久化资源
# chat 前缀的桶：用于存储聊天资源(图片语音视频等)，可以设置桶过期策略为 7 天。
qiniuObs:
  accessKey: "your_ak"
  secretKey: "your_sk"
  videoBucketName: "your_video_bucket_name"
  videoBucketUrl: "your_video_bucket_endpoint"
  imBucketName: "your_im_bucket_name"
  imBucketUrl: "your_im_bucket_endpoint"
  chatBucketName: "your_chat_bucket_name"
  chatBucketUrl: "your_chat_bucket_endpoint"
  endpoint: "your_endpoint"
  cdn: "your_cdn_domain"

# token 私钥
tokenKey: "xxxxxxxx"

# 客户端版本号。
# apk 名最好带上版本号，否则客户端可能当做缓存不下载
clientVersion:
  androidVersion: "0.1.0"
  forceUpgrade: false # 是否是需要强制升级的版本
  apkUrl: "http://localhost:8080/gtiv.apk" # apk 下载地址
